;Hook Smart Input Pro插件
;2.4.0
EQUAL,O00oOOO0|O000000o|(Ljava/lang/String;)Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE
;2.4.0+221u232
EQUAL,O00oOO|O000000o|(Ljava/lang/String;)Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE

;2.3.14-pycharm
EQUAL,O00oOO00|O000000o|(Ljava/lang/String;)Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE
;2.3.14-pycharm+221u232
EQUAL,O00oOO0o|O000000o|(Ljava/lang/String;)Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE
;2.3.14-goland
EQUAL,O00oOO0|O000000o|(Ljava/lang/String;)Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE
;2.3.14-goland+221u232
EQUAL,O00oOO00|O000000o|(Ljava/lang/String;)Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE


[Hook]
;Extra Tools Pack 2026.1.14
EQUAL,Ɉ|ӊ|(Ljava/io/File;Ljava/util/List;J)Z|RETURN_CONST|boolean:false
EQUAL,Ɉ|Ɲ|()Z|RETURN_CONST|boolean:false
EQUAL,Ɉ|ʀ|(Ljava/io/File;Ljava/util/List;J)Z|RETURN_CONST|boolean:false
EQUAL,Ɉ|ͻ|(IIB)Z|RETURN_CONST|boolean:false
EQUAL,Ɉ|Ղ|(Ljava/lang/String;)Z|RETURN_CONST|boolean:false
EQUAL,Ɉ|Ʊ|()Ljava/lang/String;|RETURN_CONST|string:
EQUAL,Ɉ|ȩ|()Ljava/lang/String;|RETURN_CONST|string:
EQUAL,Ɉ|Պ|()Z|RETURN_CONST|boolean:false
EQUAL,f|Ҫ|(Lcom/intellij/ui/LicensingFacade;)Z|RETURN_CONST|boolean:false
EQUAL,ExtraTCISettingsIDEService|getLicenseOKInCfg|()Ljava/lang/Boolean;|RETURN_CONST|java/lang/Boolean:TRUE