[Auto_Scan_Ide_Plugin_Path]
# 该配置用于，自定义插件路径启用
;EQUAL,IntelliJIdea2026.2=D:\Develop\Jetbrains\Settings\.IntelliJIdea\config\plugins

[Hide_Plugin]
EQUAL,io.zhile.research.ide-eval-resetter
EQUAL,Nasller.License
EQUAL,nasller
# EQUAL,manifold.ij

[Hide_Package]
PREFIX,com.janetfilter
PREFIX,org.objectweb.asm

[Hide_Resource]
PREFIX,/com/janetfilter

[Hide_Env]
EQUAL,IDEA_VM_OPTIONS
EQUAL,CLION_VM_OPTIONS
EQUAL,PHPSTORM_VM_OPTIONS
EQUAL,GOLAND_VM_OPTIONS
EQUAL,PYCHARM_VM_OPTIONS
EQUAL,WEBSTORM_VM_OPTIONS
EQUAL,WEBIDE_VM_OPTIONS
EQUAL,RIDER_VM_OPTIONS
EQUAL,DATAGRIP_VM_OPTIONS
EQUAL,RUBYMINE_VM_OPTIONS
EQUAL,APPCODE_VM_OPTIONS
EQUAL,DATASPELL_VM_OPTIONS
EQUAL,GATEWAY_VM_OPTIONS
EQUAL,JETBRAINS_CLIENT_VM_OPTIONS
EQUAL,JETBRAINSCLIENT_VM_OPTIONS
EQUAL,JANF_DEBUG
EQUAL,JANF_OUTPUT

[Hide_Property]
EQUAL,janf.debug
EQUAL,janf.output

[Ignore_Class]
EQUAL,com.janetfilter.core.utils.StringUtils
EQUAL,com.janetfilter.core.rulers.PrefixRuler
EQUAL,com.janetfilter.core.rulers.RegExpRuler
EQUAL,com.janetfilter.core.commons.ConfigParser
EQUAL,com.janetfilter.core.models.FilterRule

[Ignore_Resource]
EQUAL,/com/janetfilter/core/utils/StringUtils.class
EQUAL,/com/janetfilter/core/rulers/PrefixRuler.class
EQUAL,/com/janetfilter/core/rulers/RegExpRuler.class
EQUAL,/com/janetfilter/core/commons/ConfigParser.class
EQUAL,/com/janetfilter/core/models/FilterRule.class

